"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";
import TopBar from "@/components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Online-Expert",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const pathname = usePathname(); // Get the current pathname

    // Check if the route starts with /admin
    const isAdminRoute = pathname.startsWith("/admin");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {!isAdminRoute && (
          <>
            <TopBar />
            <Navbar />
          </>
        )}{" "}
        <main>{children}</main>
        {!isAdminRoute && <Footer />}{" "}
      </body>
    </html>
  );
}
